[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "todo_or_not_startout"

version = "v0.5.0-beta"
#dynamic = ["version"]

dependencies = [
    "typer",
    "typing_extensions"
]
authors = [
  { name="Trenton Young", email="askstartout@gmail.com" },
]
description = "#todoon integrates the TODOs in your codebase with your GitHub repository"
keywords = ["todo", "github"]
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Start-Out/todo-or-not"
Issues = "https://github.com/Start-Out/todo-or-not/issues"

[project.scripts]
todoon = "todo_check:typer_main"