on:
  workflow_dispatch:
jobs:
  track_pr:
    runs-on: ubuntu-latest
    environment: todo-or-not-1
    steps:
      - name: Generate token
        id: generate-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}
        run: |
          echo $app-id
        uses: actions/create-github-app-token@v1
      - name: Use API
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh api https://api.github.com/repos/Start-Out/todo-or-not/issues
