name: Generate issues with TODO-or-not

on:
  workflow_dispatch:
jobs:
  run_todoon:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.7"
      - name: Install TODO-or-not
        run: |
          python -m pip install --upgrade pip
          python -m pip install todo-or-not
      - name: Generate GH Token for todoon app
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: 853479
          private-key: ${{ secrets.TODOON_CLIENT_SECRET }}
      - name: Run TODO-or-not
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          echo "Generate GitHub issues for each problem found, but don't fail the workflow"
          todoon --mode issue --silent
